"""
ComplianceLoop — SQLAlchemy Declarative Base & Mixins
======================================================
Defines the shared base class and reusable mixins for all ORM models.

Mixins provided:
  - UUIDPrimaryKeyMixin  : UUID v4 primary key (server-generated)
  - TimestampMixin       : created_at / updated_at with automatic server-side timestamps
  - IsDemoMixin          : is_demo boolean present on every table that can exist in
                           both production and demo contexts — used as a hard filter
                           to ensure demo data NEVER appears in production queries

Design decisions:
  - All PKs are UUID v4, not integer sequences. Rationale: distributed-safe,
    non-guessable (security), and consistent with the audit trail which uses
    UUID references across tables.
  - Timestamps are TIMESTAMPTZ (timezone-aware) stored as UTC. The application
    never stores naive datetimes.
  - server_default is used for created_at so the DB sets the value even if the
    ORM layer doesn't — this is critical for the audit record's written_at field.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import Boolean, DateTime, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """
    Shared declarative base for all ComplianceLoop ORM models.

    All models inherit from this class. SQLAlchemy uses it to track
    all mapped classes and generate the metadata used by Alembic.
    """
    pass


class UUIDPrimaryKeyMixin:
    """
    Adds a UUID v4 primary key column named `id`.

    The UUID is generated server-side by PostgreSQL's gen_random_uuid()
    as the server_default, but also pre-populated by the ORM layer using
    Python's uuid.uuid4(). This means:
      - The ID is known before the INSERT (useful for audit pre-write)
      - The DB will generate one if the ORM somehow doesn't set it
    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
        nullable=False,
        comment="UUID v4 primary key — generated by application layer",
    )


class TimestampMixin:
    """
    Adds created_at and updated_at columns with automatic management.

    created_at: Set once at INSERT time. Never updated.
                server_default ensures value is set even on raw SQL inserts.
    updated_at: Updated on every UPDATE. Managed by SQLAlchemy's onupdate.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        server_default=func.now(),
        comment="UTC timestamp of record creation — set once, never updated",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        server_default=func.now(),
        onupdate=lambda: datetime.now(timezone.utc),
        comment="UTC timestamp of last update — managed automatically",
    )


class IsDemoMixin:
    """
    Adds is_demo boolean to distinguish production records from demo records.

    CRITICAL: Every query on tables with this mixin MUST filter by is_demo.
    The application layer enforces this via the context (demo mode vs prod mode).
    This is the double-safety net — even if a demo request reaches prod infra
    (should never happen given separate DBs), the is_demo flag prevents mixing.

    Default is False — production records are the default.
    """

    is_demo: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default=text("false"),
        index=True,
        comment="True for demo environment records — never mix with production",
    )